/*
 * generated by Xtext 2.16.0
 */
package sdu.mmmi.mdsd.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class MathInterpreterAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("sdu/mmmi/mdsd/parser/antlr/internal/InternalMathInterpreter.tokens");
	}
}
