/**
 * generated by Xtext 2.16.0
 */
package sdu.mmmi.mdsd.ide;

import sdu.mmmi.mdsd.ide.AbstractMathInterpreterIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class MathInterpreterIdeModule extends AbstractMathInterpreterIdeModule {
}
