/**
 * generated by Xtext 2.16.0
 */
package sdu.mmmi.mdsd.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import sdu.mmmi.mdsd.MathInterpreterRuntimeModule;
import sdu.mmmi.mdsd.MathInterpreterStandaloneSetup;
import sdu.mmmi.mdsd.ide.MathInterpreterIdeModule;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class MathInterpreterIdeSetup extends MathInterpreterStandaloneSetup {
  @Override
  public Injector createInjector() {
    MathInterpreterRuntimeModule _mathInterpreterRuntimeModule = new MathInterpreterRuntimeModule();
    MathInterpreterIdeModule _mathInterpreterIdeModule = new MathInterpreterIdeModule();
    return Guice.createInjector(Modules2.mixin(_mathInterpreterRuntimeModule, _mathInterpreterIdeModule));
  }
}
