/*
 * generated by Xtext 2.16.0
 */
package sdu.mmmi.mdsd.ui

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
class MathInterpreterUiModule extends AbstractMathInterpreterUiModule {
}
