/**
 * generated by Xtext 2.16.0
 */
package sdu.mmmi.mdsd.mathInterpreter;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Exp</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see sdu.mmmi.mdsd.mathInterpreter.MathInterpreterPackage#getExp()
 * @model
 * @generated
 */
public interface Exp extends EObject
{
} // Exp
