/*
 * generated by Xtext 2.16.0
 */
package sdu.mmmi.mdsd


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class MathInterpreterRuntimeModule extends AbstractMathInterpreterRuntimeModule {
}
