/*
 * generated by Xtext 2.16.0
 */
package sdu.mmmi.mdsd.ui;

import com.google.inject.Injector;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import sdu.mmmi.mdsd.mathinterpreter.ui.internal.MathinterpreterActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class MathInterpreterExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(MathinterpreterActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		MathinterpreterActivator activator = MathinterpreterActivator.getInstance();
		return activator != null ? activator.getInjector(MathinterpreterActivator.SDU_MMMI_MDSD_MATHINTERPRETER) : null;
	}

}
