/*
 * generated by Xtext 2.16.0
 */
package sdu.mmmi.mdsd.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import sdu.mmmi.mdsd.ide.contentassist.antlr.internal.InternalMathInterpreterParser;
import sdu.mmmi.mdsd.services.MathInterpreterGrammarAccess;

public class MathInterpreterParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(MathInterpreterGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, MathInterpreterGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getPrimaryAccess().getAlternatives(), "rule__Primary__Alternatives");
			builder.put(grammarAccess.getPlusOrMinusAccess().getAlternatives_1_0(), "rule__PlusOrMinus__Alternatives_1_0");
			builder.put(grammarAccess.getMultOrDivAccess().getAlternatives_1_0(), "rule__MultOrDiv__Alternatives_1_0");
			builder.put(grammarAccess.getMathExpAccess().getGroup(), "rule__MathExp__Group__0");
			builder.put(grammarAccess.getAtomicAccess().getGroup(), "rule__Atomic__Group__0");
			builder.put(grammarAccess.getPrimaryAccess().getGroup_0(), "rule__Primary__Group_0__0");
			builder.put(grammarAccess.getPlusOrMinusAccess().getGroup(), "rule__PlusOrMinus__Group__0");
			builder.put(grammarAccess.getPlusOrMinusAccess().getGroup_1(), "rule__PlusOrMinus__Group_1__0");
			builder.put(grammarAccess.getPlusOrMinusAccess().getGroup_1_0_0(), "rule__PlusOrMinus__Group_1_0_0__0");
			builder.put(grammarAccess.getPlusOrMinusAccess().getGroup_1_0_1(), "rule__PlusOrMinus__Group_1_0_1__0");
			builder.put(grammarAccess.getMultOrDivAccess().getGroup(), "rule__MultOrDiv__Group__0");
			builder.put(grammarAccess.getMultOrDivAccess().getGroup_1(), "rule__MultOrDiv__Group_1__0");
			builder.put(grammarAccess.getMultOrDivAccess().getGroup_1_0_0(), "rule__MultOrDiv__Group_1_0_0__0");
			builder.put(grammarAccess.getMultOrDivAccess().getGroup_1_0_1(), "rule__MultOrDiv__Group_1_0_1__0");
			builder.put(grammarAccess.getMathExpAccess().getExpAssignment_1(), "rule__MathExp__ExpAssignment_1");
			builder.put(grammarAccess.getAtomicAccess().getValueAssignment_1(), "rule__Atomic__ValueAssignment_1");
			builder.put(grammarAccess.getPlusOrMinusAccess().getOpAssignment_1_0_0_1(), "rule__PlusOrMinus__OpAssignment_1_0_0_1");
			builder.put(grammarAccess.getPlusOrMinusAccess().getOpAssignment_1_0_1_1(), "rule__PlusOrMinus__OpAssignment_1_0_1_1");
			builder.put(grammarAccess.getPlusOrMinusAccess().getRightAssignment_1_1(), "rule__PlusOrMinus__RightAssignment_1_1");
			builder.put(grammarAccess.getMultOrDivAccess().getOpAssignment_1_0_0_1(), "rule__MultOrDiv__OpAssignment_1_0_0_1");
			builder.put(grammarAccess.getMultOrDivAccess().getOpAssignment_1_0_1_1(), "rule__MultOrDiv__OpAssignment_1_0_1_1");
			builder.put(grammarAccess.getMultOrDivAccess().getRightAssignment_1_1(), "rule__MultOrDiv__RightAssignment_1_1");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private MathInterpreterGrammarAccess grammarAccess;

	@Override
	protected InternalMathInterpreterParser createParser() {
		InternalMathInterpreterParser result = new InternalMathInterpreterParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public MathInterpreterGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(MathInterpreterGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
