/**
 * generated by Xtext 2.16.0
 */
package sdu.mmmi.mdsd.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import sdu.mmmi.mdsd.ui.AbstractMathInterpreterUiModule;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class MathInterpreterUiModule extends AbstractMathInterpreterUiModule {
  public MathInterpreterUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
