/*
 * generated by Xtext 2.16.0
 */
package dk.sdu.mdsd


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class MathinterpreterStandaloneSetup extends MathinterpreterStandaloneSetupGenerated {

	def static void doSetup() {
		new MathinterpreterStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
