/**
 * generated by Xtext 2.16.0
 */
package sdu.mmmi.mdsd;

import sdu.mmmi.mdsd.AbstractMathInterpreterRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class MathInterpreterRuntimeModule extends AbstractMathInterpreterRuntimeModule {
}
