/**
 * generated by Xtext 2.16.0
 */
package sdu.mmmi.mdsd;

import sdu.mmmi.mdsd.MathInterpreterStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class MathInterpreterStandaloneSetup extends MathInterpreterStandaloneSetupGenerated {
  public static void doSetup() {
    new MathInterpreterStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
